### PR TITLE
DBZ-6602: Support record header as primary_key

### PR DESCRIPTION
**Pull request by blcksrx**
https://issues.redhat.com/browse/DBZ-6602

### CODE REVIEW

**Review by Naros — COMMENTED** [review]
Hi @blcksrx, this looks great!  Please also submit a small PR to the main Debezium repository adding this new option to the JDBC connector's documentation page.

**Comment by blcksrx** [comment]
Documentation: https://github.com/debezium/debezium/pull/4649

**Review by Naros — APPROVED** [review]
LGTM, thanks @blcksrx !

**Comment by Naros** [comment]
Applied to main (=2.4).

**Pull request merged**
